Repository Felipe-Cavalca/BifrostPHP-Components, pull requests merged in 2024-05, with the labels that each got.

#10 3 possibilidade de alterar o caminho da pasta de components
  customComponents.js
Labels: enhancement

#11 Escrevendo documentação no readme do projeto
  README.md
Labels: documentation

#12 Update README.md
  README.md
Labels: documentation

#13 Desenvolvendo demo do projeto
  demo/components/body.html
  demo/components/footer.html
  demo/components/navbar.html
  demo/components/title.html
  demo/index.html
  demo/style.css
  index.html
Labels: enhancement

#32 Vinculando arquivo min.js a release criada
  .github/workflows/minify.yml
Labels: enhancement

#33 Corrigindo caminho da arquivo a ser feito o upload
  .github/workflows/minify.yml
Labels: bug

#91 alterando release de acordo com a tag do pr
  .github/workflows/tag_on_merge.yml
Labels: enhancement

#93 Adicionando script para escrever o texto da release
  .github/workflows/tag_on_merge.yml
Labels: enhancement

#94 alterando needs da publicação da release
  .github/workflows/tag_on_merge.yml
Labels: bug

#95 apagando script que gera um rascunho
  .github/workflows/tag_on_merge.yml
Labels: bug

#96 Adicionando comentarios as funções
  src/customComponents.js
Labels: documentation

#97 puxando base para alterar funding
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/report-de-bug.md
  .github/ISSUE_TEMPLATE/solicitação-de-melhoria.md
Labels: documentation

#98 Dev
  .github/FUNDING.yml
Labels: documentation

#100 Merge base repo
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/report-de-bug.md
  .github/ISSUE_TEMPLATE/solicitação-de-melhoria.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
  .github/release-drafter.yml
  .github/workflows/tag_on_merge.yml
  SECURITY.md
Labels: enhancement, refactoring, update

#101 modified sponsors
  README.md
Labels: enhancement, upgrade

#102 excluding previous releases
  dist/customComponents-3.0.0-1.min.js
  dist/customComponents-V-1.8.5.min.js
  dist/customComponents-V-2.0.0.min.js
  dist/customComponents-V-2.1.0.min.js
  dist/customComponents-V-2.2.0.min.js
  dist/customComponents-V-2.3.0.min.js
  dist/customComponents-V-2.3.1.min.js
  dist/customComponents-V-2.3.2.min.js
  dist/customComponents-V-2.4.0.min.js
  dist/customComponents-V-2.4.1.min.js
  dist/customComponents-V-2.4.2.min.js
  dist/customComponents-V-2.4.3.min.js
Labels: enhancement, update
